
export const LOAD_CONFIG_REQUEST = '@@config/LOAD_CONFIG_REQUEST';
export const LOAD_CONFIG_SUCCESS = '@@config/LOAD_CONFIG_SUCCESS';
export const LOAD_CONFIG_ERROR = '@@config/LOAD_CONFIG_ERROR';
export const UPDATE_CONFIG_REQUEST = '@@config/UPDATE_CONFIG_REQUEST';
export const UPDATE_CONFIG_SUCCESS = '@@config/UPDATE_CONFIG_SUCCESS';
export const UPDATE_CONFIG_ERROR = '@@config/UPDATE_CONFIG_ERROR';
export const GET_EXCHANGE_RATE_REQUEST = '@@exchange/GET_EXCHANGE_RATE_REQUEST';
export const GET_EXCHANGE_RATE_SUCCESS = '@@exchange/GET_EXCHANGE_RATE_SUCCESS';
export const GET_EXCHANGE_RATE_ERROR = '@@exchange/GET_EXCHANGE_RATE_ERROR';
export const UPDATE_CURRENCY_STOCK_REQUEST = '@@currency/UPDATE_CURRENCY_STOCK_REQUEST';
export const UPDATE_CURRENCY_STOCK_SUCCESS = '@@currency/UPDATE_CURRENCY_STOCK_SUCCESS';
export const UPDATE_CURRENCY_STOCK_ERROR = '@@currency/UPDATE_CURRENCY_STOCK_ERROR';
