
export const LOAD_CONFIG_REQUEST = '@@config/LOAD_CONFIG_REQUEST';
export const LOAD_CONFIG_SUCCESS = '@@config/LOAD_CONFIG_SUCCESS';
export const LOAD_CONFIG_ERROR = '@@config/LOAD_CONFIG_ERROR';
export const GET_EXCHANGE_RATE_REQUEST = '@@exchange/GET_EXCHANGE_RATE_REQUEST';
export const GET_EXCHANGE_RATE_SUCCESS = '@@exchange/GET_EXCHANGE_RATE_SUCCESS';
export const GET_EXCHANGE_RATE_ERROR = '@@exchange/GET_EXCHANGE_RATE_ERROR';
